
* Nome do Software (ou Biblioteca):
- DESENVOLVIMENTO DO SOFTWARE CARACTERIZAÇÃO DE RESERVATÓRIOS INTEGRADO À ANÁLISE PETROFÍSICA
- ProjetoEngenharia-SoftwareCaracterizacaoDeReservatoriosIntegradoAAnalisePetrofisica

  
* Resumo e/ou informação extra: 
- Criar um software capaz de calcular parâmetros e inferir características de
um reservatório, através da análise dos dados obtidos em testes de pressão em
poços e na testemunhagem do reservatório, possibilitando estimar as dimensões
do campo e sua potencialidade econômica. Um diferencial importante nesta
versão é a flexíbilidade na entrada de dados do usuário.

* Versão: 
- 2.0.

* Data:
- 2014/2 - segundo semestre.
  
* Autor de Contato:
- André Duarte Bueno <andreduartebueno@gmail.com>

* Lista dos Autores:
- ALEXANDRE LISBOA BASTOS JUNIOR - VERSÃO 2 (2014/2)
- JOÃO VITOR MARINHO DA COSTA NEVES - VERSÃO 2 (2014/2)
- MAXIMIANO KANDA FERRAZ - VERSÃO 1 (2012/2)
- GABRIEL VASCONCELOS DE SOUSA - VERSÃO 1 (2012/2)
- André Duarte Bueno <andreduartebueno@gmail.com>

* Áreas de pesquisa vinculadas: 
- Modelagem Matemática Computacional
- Engenharia Reservatório

* Vinculo com: 
- Trabalho da disciplina de programação prática.

* Paradigmas: 
- POO - Programação Orientada a Objeto (códigos em C++)

* Tipo de Interface: 
- Terminal e gráfica (gnuplot).

* Plataformas Suportadas: 
- Windows e GNU/Linux e Mac OS X (não testada).

* Linguagens Utilizadas: 
- C++ 11.

* Bibliotecas Utilizadas (dependências):
- CGnuplot - https://github.com/ldsc/CGnuplot

* Softwares utilizados (dependências)
- gnuplot http://www.gnuplot.info/

* Tipo de Licença:
- GPL
- Entre em contato com o Prof. André Duarte Bueno
  andreduartebueno@gmail.com
  para que o mesmo gere um novo projeto no github do ldsc para que você (e sua equipe) possam trabalhar na nova versão.
- Se este projeto tem como número de versão 1.0 a nova versão deverá ser 2.0 e assim sucessivamente.
- Os nomes dos autores originais deve ser preservada na nova versão, ou seja, adicione a informação do número da versão, os nomes dos membros da nova equipe, mas jamais apague os nomes dos autores originais (isto seria plágio).
- Na descrição do projeto informe que trata-se de uma nova versão, que tem como base a versão anterior e DESTAQUE COM CLAREZA E OBJETIVIDADE QUAIS AS NOVIDADES DA NOVA VERSÃO.
  
* Links:

